{
    'name': 'Hospital',
    'version': '15.0.1.0.0',
    'summary': 'Hospital App',
    'author': 'Rostyslav Prorochenko',
    'website': 'https://www.odoo.com',
    'license': 'LGPL-3',
    'category': 'Extra Tools',
    'data': [
        'security/ir.model.access.csv',
        'data/disease_data.xml',
        'views/menu.xml',
        'views/visit.xml',
        'views/doctor.xml',
        'views/patient.xml',
        'views/disease.xml',
    ],
    'demo': [
        'data/doctor_demo.xml',
        'data/patient_demo.xml',
    ],
    'application': False,
    'installable': True,
    'auto_install': False,
}
